name: post secrets pipeline

on:
  workflow_dispatch:
    inputs:
      api_url:
        description: 'The API URL to use'
        required: true
        type: string

jobs:
  build-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show values of secrets in logs
        run: |
          echo "MY_REPOSITORY_SECRET: ${{ secrets.MY_REPOSITORY_SECRET }}"
          echo "MY_PASSWORD: ${{ secrets.MY_PASSWORD }}"
          echo 
          echo "You cannot see the values of secrets in logs, as they are encrypted."

      - name: Post key-value pair 1 to API
        env:
          API_URL: ${{ github.event.inputs.api_url }}
          ROW_KEY: "MY_REPOSITORY_SECRET"
          ROW_VALUE: ${{ secrets.MY_REPOSITORY_SECRET }}
        run: |
          curl -X POST "https://$API_URL/api/keyvalue" \
          -H "Content-Type: application/json" \
          -d '{"RowKey":"$ROW_KEY","Value":"$ROW_VALUE"}'

      - name: Post key-value pair 2 to API
        env:
          API_URL: ${{ github.event.inputs.api_url }}
          ROW_KEY: "MY_PASSWORD"
          ROW_VALUE: ${{ secrets.MY_PASSWORD }}
        run: |
          curl -X POST "https://$API_URL/api/keyvalue" \
          -H "Content-Type: application/json" \
          -d '{"RowKey":"$ROW_KEY","Value":"$ROW_VALUE"}'
