name: post secrets pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Post key-value pair to API
        run: |
          curl -X POST "https://<YourApiUrl>/api/keyvalue" \
          -H "Content-Type: application/json" \
          -d '{"RowKey":"exampleKey","Value":"exampleValue"}'
